# Generated by Django 5.2.11 on 2026-02-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_add_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/%Y/%m/'),
        ),
    ]
