# Generated by Django 4.2.30 on 2026-06-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='liveevent',
            index=models.Index(fields=['invite_token'], name='live_liveev_invite__4ee4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='liveevent',
            index=models.Index(fields=['status', 'ends_at'], name='live_liveev_status_8aaaed_idx'),
        ),
        migrations.AddIndex(
            model_name='liveparticipantprogress',
            index=models.Index(fields=['live_event', 'session_key'], name='live_livepa_live_ev_77ddd9_idx'),
        ),
        migrations.AddIndex(
            model_name='livevote',
            index=models.Index(fields=['live_event', 'template_item'], name='live_livevo_live_ev_14c3b6_idx'),
        ),
    ]
