# Generated by Django 5.2.11 on 2026-02-21 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierListReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('wow', 'Wow'), ('sad', 'Sad')], max_length=10)),
                ('tier_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='lists.tierlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_list_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tier_list', 'reaction_type'], name='lists_tierl_tier_li_9561d3_idx')],
                'unique_together': {('tier_list', 'user')},
            },
        ),
    ]
