# Generated by Django 5.2.11 on 2026-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_add_tierlist_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierlist',
            name='row_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
