# Generated by Django 5.2.11 on 2026-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_add_row_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierlist',
            name='custom_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tierlist',
            name='label_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
