# Generated by Django 5.2.11 on 2026-04-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_add_label_overrides_and_custom_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="tierlist",
            name="color_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

